http://localhost:8002/api/orders/10250
###
http://localhost:8002/api/orders/20250

###
http://localhost:8003/api/shippers/3
###
http://localhost:8003/api/shippers/12

###
http://localhost:8004/api/employees/1
###
http://localhost:8001/api/customers/ALFKI

###
GET /api/orders/10250
Host: localhost:8002
Accept: application/xml
###

http://localhost:8080/api/products/41